name: samtools_splitheader
description: Extract header lines from a SAM/BAM/CRAM file into separate files
  depending on type
keywords:
  - view
  - bam
  - sam
  - cram
  - readgroup
  - program
  - sequence
  - header
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:samtools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: http://edamontology.org/format_2573 # SAM
          - edam: http://edamontology.org/format_2572 # BAM
          - edam: http://edamontology.org/format_3462 # CRAM
output:
  readgroup:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_readgroups.txt":
          type: file
          description: |
            Text file containing read group (@RG) lines from SAM header
          ontologies:
            - edam: http://edamontology.org/format_3462 # Text
  programs:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_programs.txt":
          type: file
          description: |
            Text file containing program (@PG) lines from SAM header
          ontologies:
            - edam: http://edamontology.org/format_3462 # Text
  sequences:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_sequences.txt":
          type: file
          description: |
            Text file containing sequence (@SQ) lines from SAM header
          ontologies:
            - edam: http://edamontology.org/format_3462 # Text
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@matthdsm"
  - "@prototaxites"
maintainers:
  - "@matthdsm"
  - "@prototaxites"
