name: kallisto_quant
description: gene/transcript quantification with kallisto
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - kallisto:
      description: Quantifying abundances of transcripts from RNA-Seq data, or more generally of target sequences using high-throughput sequencing reads.
      homepage: https://pachterlab.github.io/kallisto/about
      documentation: https://pachterlab.github.io/kallisto/manual
      tool_dev_url: None
      doi: https://doi.org/10.1038/nbt.3519
      licence: ['BSD_2_clause']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
  - index:
      type: directory
      description: Folder containing the star index files
  - gtf:
      type: file
      description: GTF of the reference transcriptome
  - transcriptome_fasta:
      type: file
      description: Fasta file of the reference transcriptome
  - alignment_mode:
      type: boolean
      description: whether to run kallisto in alignment mode

output:
  - sample_output:
      type: directory
      description: Folder containing the quantification results for a specific sample
      pattern: "${prefix}"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"


authors:
  - "@BatoolMM"
