name: kallisto_index
description: Create index for kallisto
keywords:
  - fasta
  - genome
  - reference
  - index
tools:
  - kallisto:
      description: Quantifying abundances of transcripts from RNA-Seq data, or more generally of target sequences using high-throughput sequencing reads.
      homepage: https://pachterlab.github.io/kallisto/about
      documentation: https://pachterlab.github.io/kallisto/manual
      tool_dev_url: None
      doi: https://doi.org/10.1038/nbt.3519
      licence: ['BSD_2_clause']

input:
  - genome_fasta:
      type: file
      description: Fasta file of the reference genome
  - transcriptome_fasta:
      type: file
      description: Fasta file of the reference transcriptome

output:
  - index:
      type: directory
      description: Folder containing the star index files
      pattern: "kallisto"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@BatoolMM"
