# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "bamstats_generalstats"
description: write your description here
keywords:
  - bam
  - statistics
  - genomics
tools:
  - "bamstats":
      description: "A command line tool to compute mapping statistics from a BAM file"
      homepage: "https://github.com/guigolab/bamstats/"
      documentation: "https://github.com/guigolab/bamstats/"
      tool_dev_url: "https://github.com/guigolab"
      licence: ["BSD-3-clause"]
      identifier: biotools:bamstats-ip

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - bam:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies: []
output:
  json:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.json":
          type: file
          description: json containing bam statistics
          pattern: "*.json"
          ontologies:
            - edam: http://edamontology.org/format_3464 # JSON
  versions_bamstats:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bamstats:
          type: string
          description: The name of the tool
      - 'bamstats --version | grep "version: " | sed -e s"/version: //':
          type: string
          description: The version of the tool
topics:
  - versions:
      - - process:
            type: string
            description: The process the versions were collected from
        - tool:
            type: string
            description: The tool name
        - version:
            type: string
            description: The version of the tool
authors:
  - "@johnoooh"
