# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "vembrane_table"
description: Creates tabular (TSV) files from VCF/BCF data with flexible Python expressions
keywords:
  - vcf
  - bcf
  - table
  - genomics
  - variant
  - annotation
tools:
  - "vembrane":
      description: "Filter VCF/BCF files with Python expressions"
      homepage: "https://vembrane.github.io/"
      documentation: "https://github.com/vembrane/vembrane/blob/main/docs/table.md"
      tool_dev_url: "https://github.com/vembrane/vembrane"
      doi: "10.1093/bioinformatics/btac810"
      licence: ["MIT"]
      identifier: biotools:vembrane
      args_id: "$args"

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - vcf:
        type: file
        description: VCF/BCF file to extract tabular data from
        pattern: "*.{vcf,vcf.gz,bcf,bcf.gz}"
        ontologies:
          - edam: http://edamontology.org/format_3016 # VCF
  - expression:
      type: string
      description: A comma-separated tuple of expressions that define the table column contents

output:
  table:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.tsv":
          type: file
          description: TSV file containing tabular data from VCF/BCF
          pattern: "*.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
- "@mkatsanto"
- "@trangdo-hsc"
maintainers:
- "@mkatsanto"
- "@trangdo-hsc"
